### ISSUE TITLE
Update iconv dependency in package.json

### ISSUE THREAD

**Issue by cookiengineer** [TooTallNate/ref-wchar#3]
Please update the iconv dependency, because it is currently broken with node v6+.

Relevant issue is this one: https://github.com/bnoordhuis/node-iconv/issues/157#issuecomment-223305847

**Comment by cookiengineer** [comment]
@TooTallNate It would be awesome to get a ref-wchar 1.0.2 pushed out, so the fix lands for all people without a shrinkwrap json file.

**Comment by cookiengineer** [comment]
Any updates on this? It's still broken in production and this is a very low hanging fruit.

**Comment by TooTallNate** [comment]
v1.0.2 published. Sorry for the delay!

**Comment by cookiengineer** [comment]
Awesome, thank you!
